### ISSUE TITLE
Tetris theme and style

### ISSUE THREAD

**Issue by anvial** [chrum/ngx-tetris#1]
Is there any API to change size/style/colors of tetris-core objects? 

Thank You.

**Comment by chrum** [comment]
hey, 

at the moment not really... i can try to add those if you need them

**Comment by anvial** [comment]
Hi, thank you for your app. I find it very cool!

I use it as a 'easter-egg' in my project. Aka "Dinosaur-game" in Google Chrome. 

But sometimes it badly looks on small screens (for ex. macbook pro 13'). 

That's why I ask you question about styles.

**Comment by chrum** [comment]
i created this lib so i can use it in my angular workshops... 
but its so cool that you find it useful too :)

**Comment by chrum** [comment]
hey,

Added support for tiles size change and colors :D 
check the demo https://chrum.it/pages/ngx-tetris/
and new version !

let me know what you think :)
